implemented load function
nebuly-ai/nebullvm pull request #135
Opened 2023-01-04 15:40 UTC by ZecchinLeonardo

closes issue #130, implemented load function and updated tests, implemented save and load functions for yolov5

2023-01-05 09:02 UTC, valeriosofi requested changes

2023-01-19 14:03 UTC, valeriosofi requested changes

2023-01-19 16:55 UTC, valeriosofi requested changes

2023-01-19 16:55 UTC, valeriosofi commented on nebullvm/operations/optimizations/utils.py
> +from typing import Callable, List, Union
pathlib and typing should be in the first block and sorted ;)
nebullvm import should be in the second block

2023-01-20 09:15 UTC, diegofiori commented
Just a couple of comments:
1. For the sake of symmetry, can we also implement a `save_model` function? Something like
```python
def save_model(optimized_model: BaseInferenceLearner, path: Union[str, Path]):
    optimized_model.save(path)
``` 
2. We should import the load_model and save_model functions in speedster `__init__.py` file. In this way the user can import them directly from speedster with 
```python
from speedster import optimize_model, save_model, load_model
```

2023-01-20 15:00 UTC, diegofiori commented
And don't forget to update both the `readme` and the `documentation` with the new `load_model` and `save_model` functions.

2023-01-22 15:04 UTC, merged