Added documentation to Open Alpha Tensor modules and methods
nebuly-ai/nebullvm pull request #146
Opened 2023-01-10 23:07 UTC by BrianPulfer

Solving issue #138 .

2023-01-11 10:17 UTC, diegofiori requested changes
Hello @BrianPulfer! Thanks for your contribution! You made a really good job! I just left few comments about a couple of argument descriptions. The majority of my comments are just about adapting the documentation to the style we used on the main repository, `nebullvm`. 

Furthermore, please, check out the [Coding Style section in the Contribution Guidelines](https://github.com/nebuly-ai/nebullvm/blob/main/CONTRIBUTING.md#coding-style) and make sure you have configured your environment correctly (I saw a couple of changes in the code format).

2023-01-12 14:39 UTC, diegofiori reviewed
Hello @BrianPulfer, I left a couple of minor comments. Just one thing, be sure to have properly installed the pre-commit library in your environment and to have it properly configured following [these guidelines](https://github.com/nebuly-ai/nebullvm/blob/main/CONTRIBUTING.md#coding-style).

2023-01-12 16:57 UTC, diegofiori commented
@BrianPulfer I saw that you resolved my previous comments, but I don't see any modification into the code. Did you push it?

2023-01-12 20:49 UTC, BrianPulfer commented
> @BrianPulfer I saw that you resolved my previous comments, but I don't see any modification into the code. Did you push it?

Hi @diegofiori! Yes, sorry about that, I still did not commit those changes yet because of an issue in my environment regarding the pre-commit hooks. Could it be that there's an error in the [.pre-commit-config.yaml](https://github.com/nebuly-ai/nebullvm/blob/main/.pre-commit-config.yaml ) file? It seems to point to flake8's GitLab repo (which doesn't exist). Is this a mistake?

2023-01-13 14:09 UTC, diegofiori commented
Hello @BrianPulfer, I pushed a couple of fixes for preventing an excessive memory consumption during training. It creates a couple of conflicts with your code, but they should be quick to be solved. I updated the pre-commit config file too. So, now you should be able to install the hook correctly.

2023-01-14 16:12 UTC, diegofiori reviewed
Thanks for the contribution @BrianPulfer! I think there have been a couple of problems while fixing the merge conflicts. I just left few comments where the modifications need to be reverted.

2023-01-14 16:12 UTC, diegofiori commented on apps/accelerate/open_alpha_tensor/open_alpha_tensor/core/actors/stage.py
> +    return reducing_tensor[:, indexes], cloned_idx_to_idx_map, indexes
please keep the old code modification (the code in red should replace the code in green)

2023-01-14 16:12 UTC, diegofiori commented on apps/accelerate/open_alpha_tensor/open_alpha_tensor/core/actors/stage.py
> +    )
please keep the old code modification (the code in red should replace the code in green)

2023-01-14 16:12 UTC, diegofiori commented on apps/accelerate/open_alpha_tensor/open_alpha_tensor/core/actors/stage.py
>      )
please keep the old code modification (the code in red should replace the code in green)

2023-01-14 16:12 UTC, diegofiori commented on apps/accelerate/open_alpha_tensor/open_alpha_tensor/core/actors/stage.py
> +    repetitions: Dict[int, int],
please keep the old code modification (the code in red should replace the code in green)

2023-01-14 16:12 UTC, diegofiori commented on apps/accelerate/open_alpha_tensor/open_alpha_tensor/core/actors/stage.py
> +        [repetitions.get(i, 0) for i in range(len(possible_states))]
please keep the old code modification (the code in red should replace the code in green)

2023-01-14 16:12 UTC, diegofiori commented on apps/accelerate/open_alpha_tensor/open_alpha_tensor/core/actors/stage.py
> +            possible_states,
please keep the old code modification (the code in red should replace the code in green)

2023-01-14 16:12 UTC, diegofiori commented on apps/accelerate/open_alpha_tensor/open_alpha_tensor/core/actors/stage.py
> -        )[0]
please keep the old code modification (the code in red should be inserted back)

2023-01-14 16:12 UTC, diegofiori commented on apps/accelerate/open_alpha_tensor/open_alpha_tensor/core/actors/stage.py
> -                cloned_idx_to_idx,
please keep the old code modification (the code in red should be inserted back)

2023-01-14 16:12 UTC, diegofiori commented on apps/accelerate/open_alpha_tensor/open_alpha_tensor/core/actors/stage.py
> +                [s.to("cpu") for s in possible_states],
please keep the old code modification (the code in red should replace the code in green)

2023-01-14 16:12 UTC, diegofiori commented on apps/accelerate/open_alpha_tensor/open_alpha_tensor/core/actors/stage.py
> +            ]
please keep the old code modification (the code in red should replace the code in green)

2023-01-14 16:12 UTC, diegofiori commented on apps/accelerate/open_alpha_tensor/open_alpha_tensor/core/actors/stage.py
> +                not_dupl_index = repetitions[int(action_idx)]
please keep the old code modification (the code in red should replace the code in green)

2023-01-14 16:12 UTC, diegofiori commented on apps/accelerate/open_alpha_tensor/open_alpha_tensor/core/actors/stage.py
> +            N_s_a = state_dict[state_hash][2]
please keep the old code modification (the code in red should replace the code in green)

2023-01-14 16:12 UTC, diegofiori commented on apps/accelerate/open_alpha_tensor/open_alpha_tensor/core/actors/stage.py
> +    possible_states, repetitions, N_s_a, q_values, _ = state_dict[state_hash]
please keep the old code modification (the code in red should replace the code in green)

2023-01-14 16:12 UTC, diegofiori commented on apps/accelerate/open_alpha_tensor/open_alpha_tensor/core/actors/stage.py
> +        actions = state_dict[state][4]
please keep the old code modification (the code in red should replace the code in green)

2023-01-14 16:12 UTC, diegofiori commented on apps/accelerate/open_alpha_tensor/open_alpha_tensor/core/actors/stage.py
> +        actions = [state_dict[hash_state][4] for hash_state in hash_states]
please keep the old code modification (the code in red should replace the code in green)

2023-01-15 17:16 UTC, BrianPulfer commented
Hi @diegofiori. I should have figured it out. Sorry for the unnecessarily many commits 😅. It should all be good now.

2023-01-15 17:36 UTC, diegofiori approved these changes
Thanks @BrianPulfer for your contribution! Very much appreciated. Since your contribution was super valuable, I'm going to send over some swags from the community. Also, I would be very happy to work together on adding more features to the `open_alpha_tensor` module. 

I was planning to add the following features:
- [ ] Action to Code conversion: Convert the model outputs (sequence of actions) into a code for solving matrix multiplication
- [ ] Function for running the AlphaTensor model at inference time, using n actors working on n different basis
- [ ] Convert results obtained in different basis to the original one
- [ ] Improve the speed of the acting step, which is right now the main bottleneck while training the model.

Let me know if you are interested in implementing any of them!

2023-01-15 17:38 UTC, merged